object Versions{
    const val compose = "1.2.0"
    const val composeMaterial3 = "1.1.0"
    const val composeCompiler = "1.4.6"
    const val hilt = "2.42"
    const val okHttp = "4.9.3"
    const val serial = "1.3.2"
    const val retrofit = "2.9.0"
    const val room = "2.5.0"
    const val navigation = "2.4.2-beta02"
    const val hiltNavigation = "1.1.0-alpha01"
    const val lifecycle ="2.4.0"
    const val reflect = "1.5.31"
    const val reflection = "0.10.2"
    const val ktor = "1.6.3"
    const val hiltWork ="1.0.0"
    const val navigation1 = "2.4.1"
    const val coro = "1.6.0"
}